#服务的端口号
server:
  port: 9100
spring:
  application:
    name: config-server #服务名称
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ruihuihui/test1101.git #配置文件所在仓库
          username: 13783083510#登录账号
          password: rui19960306.521 #登录密码
          default-label: master #配置文件分支

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true